[project]
name = "ia-ract"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain[google-genai]>=1.0.0a10",
    "pyright>=1.1.406",
    "requests>=2.32.5",
    "ruff>=0.13.2",
]
